'use strict';

const assert = require('assert');
const childProcess = require('child_process');
const fs = require('fs');
const test = require('node:test');
const path = require('path');
const { runCli } = require('../src/cli');
const { createTempWorkspace } = require('./helpers/temp-workspace');

function createLegacyFixture() {
  const workspace = createTempWorkspace();
  workspace.writeText('components/language/node.gitignore', 'node_modules/\n');
  workspace.writeJson('presets/node.json', {
    components: ['language/node']
  });
  workspace.writeJson('projects.json', {
    projects: [
      {
        root: 'examples',
        name: 'demo',
        preset: 'node',
        custom: ['.env']
      }
    ]
  });
  return workspace;
}

test('help prints the implemented command groups', async () => {
  const writes = [];
  const result = await runCli(['help'], {
    stdout: { write: (text) => writes.push(String(text)) },
    stderr: { write: () => {} },
    cwd: process.cwd()
  });

  assert.equal(result.exitCode, 0);
  const output = writes.join('');
  assert.match(output, /ignorekit/);
  assert.match(output, /generate <config>/);
  assert.match(output, /init <project-path>/);
  assert.match(output, /adopt <project-path>/);
  assert.match(output, /extract component <id>/);
  assert.match(output, /preset create <name>/);
});

test('unknown command returns exit code 1', async () => {
  const errors = [];
  const result = await runCli(['unknown-command'], {
    stdout: { write: () => {} },
    stderr: { write: (text) => errors.push(String(text)) },
    cwd: process.cwd()
  });

  assert.equal(result.exitCode, 1);
  assert.match(errors.join(''), /Unknown command/);
});

test('legacy list command is delegated', async () => {
  const workspace = createLegacyFixture();
  try {
    const writes = [];
    const errors = [];
    const result = await runCli(['list', 'components'], {
      stdout: { write: (text) => writes.push(String(text)) },
      stderr: { write: (text) => errors.push(String(text)) },
      cwd: workspace.root,
      repoRoot: workspace.root
    });

    assert.equal(result.exitCode, 0);
    assert.equal(errors.join(''), '');
    const output = writes.join('');
    assert.match(output, /Components:/);
    assert.match(output, /language\/node/);
  } finally {
    workspace.cleanup();
  }
});

test('legacy build all command is delegated', async () => {
  const workspace = createLegacyFixture();
  try {
    const writes = [];
    const errors = [];
    const result = await runCli(['build', '--all'], {
      stdout: { write: (text) => writes.push(String(text)) },
      stderr: { write: (text) => errors.push(String(text)) },
      cwd: workspace.root,
      repoRoot: workspace.root
    });

    assert.equal(result.exitCode, 0);
    assert.equal(errors.join(''), '');
    assert.match(writes.join(''), /Generated/);
    const generated = workspace.readText('generated/examples/demo.gitignore');
    assert.match(generated, /Generated by ignorekit/);
    assert.match(generated, /node_modules\//);
    assert.match(generated, /\.env/);
  } finally {
    workspace.cleanup();
  }
});

test('legacy command errors return exit code 1', async () => {
  const workspace = createLegacyFixture();
  try {
    const errors = [];
    const result = await runCli(['list', 'unknown-target'], {
      stdout: { write: () => {} },
      stderr: { write: (text) => errors.push(String(text)) },
      cwd: workspace.root,
      repoRoot: workspace.root
    });

    assert.equal(result.exitCode, 1);
    assert.match(errors.join(''), /Unknown list target/);
  } finally {
    workspace.cleanup();
  }
});

test('wrapper reports rejected runCli errors without stack traces', () => {
  const workspace = createTempWorkspace();
  try {
    const wrapperPath = path.join(__dirname, '..', 'bin', 'ignorekit.js');
    workspace.writeText('bin/ignorekit.js', fs.readFileSync(wrapperPath, 'utf8'));
    workspace.writeText('src/cli.js', `'use strict';

async function runCli() {
  throw new Error('boom');
}

module.exports = { runCli };
`);

    const result = childProcess.spawnSync(process.execPath, [workspace.path('bin', 'ignorekit.js')], {
      encoding: 'utf8'
    });

    assert.equal(result.status, 1);
    assert.equal(result.stdout, '');
    assert.equal(result.stderr, 'ignorekit: boom\n');
  } finally {
    workspace.cleanup();
  }
});
