'use strict';

const assert = require('assert');
const test = require('node:test');
const { createTempWorkspace } = require('./helpers/temp-workspace');
const { createDefinitionResolver } = require('../src/definitions/resolver');
const { generateGitignore } = require('../src/generator');

test('generator combines provider text, preset components, config components, and custom rules', async () => {
  const workspace = createTempWorkspace();
  try {
    workspace.writeText('dist/components/local/logs.gitignore', 'logs/\n*.log\n');
    workspace.writeText('dist/components/local/secrets.gitignore', '.env\n');
    workspace.writeJson('dist/presets/demo.json', {
      name: 'demo',
      components: ['local/logs']
    });

    const resolver = createDefinitionResolver({ distRoot: workspace.path('dist') });
    const content = await generateGitignore({
      config: {
        version: 1,
        name: 'demo-project',
        preset: 'demo',
        provider: { name: 'local' },
        components: ['local/secrets'],
        custom: ['/runtime/'],
        addons: {}
      },
      resolver
    });

    assert.match(content, /Generated by ignorekit/);
    assert.match(content, /Preset: demo/);
    assert.match(content, /logs\//);
    assert.match(content, /\.env/);
    assert.match(content, /\/runtime\//);
  } finally {
    workspace.cleanup();
  }
});

test('generator works without a preset', async () => {
  const workspace = createTempWorkspace();
  try {
    workspace.writeText('dist/components/local/logs.gitignore', 'logs/\n');

    const resolver = createDefinitionResolver({ distRoot: workspace.path('dist') });
    const content = await generateGitignore({
      config: {
        version: 1,
        name: 'no-preset-project',
        provider: { name: 'local' },
        components: ['local/logs'],
        custom: [],
        addons: {}
      },
      resolver
    });

    assert.match(content, /Preset: none/);
    assert.match(content, /logs\//);
  } finally {
    workspace.cleanup();
  }
});

test('generator includes provider text when provider is gitignore.io', async () => {
  const workspace = createTempWorkspace();
  try {
    workspace.writeJson('dist/presets/demo.json', {
      name: 'demo',
      components: []
    });

    const resolver = createDefinitionResolver({ distRoot: workspace.path('dist') });
    const content = await generateGitignore({
      config: {
        version: 1,
        name: 'provider-test',
        preset: 'demo',
        provider: { name: 'gitignore.io', templates: ['java'] },
        custom: [],
        addons: {}
      },
      resolver,
      providerOptions: {
        fetchText: async () => '#!! Java\n*.class\n'
      }
    });

    assert.match(content, /Provider templates/);
    assert.match(content, /\*\.class/);
  } finally {
    workspace.cleanup();
  }
});

test('generator resolves base chain for preset components', async () => {
  const workspace = createTempWorkspace();
  try {
    workspace.writeText('dist/components/platform/macos.gitignore', '.DS_Store\n');
    workspace.writeText('dist/components/language/node.gitignore', 'node_modules/\n');
    workspace.writeText('dist/components/framework/vite.gitignore', 'dist/\n');
    workspace.writeJson('dist/presets/generic.json', {
      name: 'generic',
      components: ['platform/macos']
    });
    workspace.writeJson('dist/presets/node.json', {
      name: 'node',
      base: 'generic',
      components: ['language/node']
    });
    workspace.writeJson('dist/presets/vite.json', {
      name: 'vite',
      base: 'node',
      components: ['framework/vite']
    });

    const resolver = createDefinitionResolver({ distRoot: workspace.path('dist') });
    const content = await generateGitignore({
      config: {
        version: 1,
        name: 'vite-project',
        preset: 'vite',
        provider: { name: 'local' },
        components: [],
        custom: [],
        addons: {}
      },
      resolver
    });

    // Should include components from all levels of the chain
    assert.match(content, /\.DS_Store/);   // from generic
    assert.match(content, /node_modules\//); // from node
    assert.match(content, /dist\//);         // from vite
    assert.match(content, /Preset: vite/);
  } finally {
    workspace.cleanup();
  }
});

test('generator excludes components from preset via exclude field', async () => {
  const workspace = createTempWorkspace();
  try {
    workspace.writeText('dist/components/platform/macos.gitignore', '.DS_Store\n');
    workspace.writeText('dist/components/language/node.gitignore', 'node_modules/\n');
    workspace.writeJson('dist/presets/node.json', {
      name: 'node',
      components: ['platform/macos', 'language/node']
    });

    const resolver = createDefinitionResolver({ distRoot: workspace.path('dist') });
    const content = await generateGitignore({
      config: {
        version: 1,
        name: 'exclude-test',
        preset: 'node',
        exclude: ['platform/macos'],
        provider: { name: 'local' },
        components: [],
        custom: [],
        addons: {}
      },
      resolver
    });

    // Should include language/node but NOT platform/macos
    assert.match(content, /node_modules\//);
    assert.doesNotMatch(content, /\.DS_Store/);
    // Should still reference the preset
    assert.match(content, /Preset: node/);
  } finally {
    workspace.cleanup();
  }
});
