'use strict';

const assert = require('assert');
const test = require('node:test');
const { createTempWorkspace } = require('./helpers/temp-workspace');
const { createDefinitionResolver } = require('../src/definitions/resolver');
const { generateGitignore } = require('../src/generator');

test('generator combines provider text, preset components, config components, and custom rules', async () => {
  const workspace = createTempWorkspace();
  try {
    workspace.writeText('dist/components/local/logs.gitignore', 'logs/\n*.log\n');
    workspace.writeText('dist/components/local/secrets.gitignore', '.env\n');
    workspace.writeJson('dist/presets/demo.json', {
      name: 'demo',
      components: ['local/logs']
    });

    const resolver = createDefinitionResolver({ distRoot: workspace.path('dist') });
    const content = await generateGitignore({
      config: {
        version: 1,
        name: 'demo-project',
        preset: 'demo',
        provider: { name: 'local' },
        components: ['local/secrets'],
        custom: ['/runtime/'],
        addons: {}
      },
      resolver
    });

    assert.match(content, /Generated by ignorekit/);
    assert.match(content, /Preset: demo/);
    assert.match(content, /logs\//);
    assert.match(content, /\.env/);
    assert.match(content, /\/runtime\//);
  } finally {
    workspace.cleanup();
  }
});

test('generator works without a preset', async () => {
  const workspace = createTempWorkspace();
  try {
    workspace.writeText('dist/components/local/logs.gitignore', 'logs/\n');

    const resolver = createDefinitionResolver({ distRoot: workspace.path('dist') });
    const content = await generateGitignore({
      config: {
        version: 1,
        name: 'no-preset-project',
        provider: { name: 'local' },
        components: ['local/logs'],
        custom: [],
        addons: {}
      },
      resolver
    });

    assert.match(content, /Preset: none/);
    assert.match(content, /logs\//);
  } finally {
    workspace.cleanup();
  }
});

test('generator includes provider text when provider is gitignore.io', async () => {
  const workspace = createTempWorkspace();
  try {
    workspace.writeJson('dist/presets/demo.json', {
      name: 'demo',
      components: []
    });

    const resolver = createDefinitionResolver({ distRoot: workspace.path('dist') });
    const content = await generateGitignore({
      config: {
        version: 1,
        name: 'provider-test',
        preset: 'demo',
        provider: { name: 'gitignore.io', templates: ['java'] },
        custom: [],
        addons: {}
      },
      resolver,
      providerOptions: {
        fetchText: async () => '#!! Java\n*.class\n'
      }
    });

    assert.match(content, /Provider templates/);
    assert.match(content, /\*\.class/);
  } finally {
    workspace.cleanup();
  }
});
