'use strict';

const assert = require('assert');
const test = require('node:test');
const { createTempWorkspace } = require('./helpers/temp-workspace');
const { createDefinitionResolver } = require('../src/definitions/resolver');
const { generateGitignore } = require('../src/generator');

test('generator combines preset components, config components, and custom rules', async () => {
  const workspace = createTempWorkspace();
  try {
    workspace.writeText('dist/components/local/logs.gitignore', 'logs/\n*.log\n');
    workspace.writeText('dist/components/local/secrets.gitignore', '.env\n');
    workspace.writeJson('dist/presets/demo.json', {
      name: 'demo',
      components: ['local/logs']
    });

    const resolver = createDefinitionResolver({ distRoot: workspace.path('dist') });
    const content = await generateGitignore({
      config: {
        version: 1,
        name: 'demo-project',
        preset: 'demo',
        provider: { name: 'local' },
        components: ['local/secrets'],
        custom: ['/runtime/'],
        addons: {}
      },
      resolver
    });

    assert.match(content, /Generated by ignorekit/);
    assert.match(content, /Preset: demo/);
    assert.match(content, /logs\//);
    assert.match(content, /\.env/);
    assert.match(content, /\/runtime\//);
  } finally {
    workspace.cleanup();
  }
});

test('generator works without a preset', async () => {
  const workspace = createTempWorkspace();
  try {
    workspace.writeText('dist/components/local/logs.gitignore', 'logs/\n');

    const resolver = createDefinitionResolver({ distRoot: workspace.path('dist') });
    const content = await generateGitignore({
      config: {
        version: 1,
        name: 'no-preset-project',
        provider: { name: 'local' },
        components: ['local/logs'],
        custom: [],
        addons: {}
      },
      resolver
    });

    assert.match(content, /Preset: none/);
    assert.match(content, /logs\//);
  } finally {
    workspace.cleanup();
  }
});

test('generator resolves base chain for preset components', async () => {
  const workspace = createTempWorkspace();
  try {
    workspace.writeText('dist/components/platform/macos.gitignore', '.DS_Store\n');
    workspace.writeText('dist/components/language/node.gitignore', 'node_modules/\n');
    workspace.writeText('dist/components/framework/vite.gitignore', 'dist/\n');
    workspace.writeJson('dist/presets/generic.json', {
      name: 'generic',
      components: ['platform/macos']
    });
    workspace.writeJson('dist/presets/node.json', {
      name: 'node',
      base: 'generic',
      components: ['language/node']
    });
    workspace.writeJson('dist/presets/vite.json', {
      name: 'vite',
      base: 'node',
      components: ['framework/vite']
    });

    const resolver = createDefinitionResolver({ distRoot: workspace.path('dist') });
    const content = await generateGitignore({
      config: {
        version: 1,
        name: 'vite-project',
        preset: 'vite',
        provider: { name: 'local' },
        components: [],
        custom: [],
        addons: {}
      },
      resolver
    });

    // Should include components from all levels of the chain
    assert.match(content, /\.DS_Store/);   // from generic
    assert.match(content, /node_modules\//); // from node
    assert.match(content, /dist\//);         // from vite
    assert.match(content, /Preset: vite/);
  } finally {
    workspace.cleanup();
  }
});

test('generator excludes components from preset via exclude field', async () => {
  const workspace = createTempWorkspace();
  try {
    workspace.writeText('dist/components/platform/macos.gitignore', '.DS_Store\n');
    workspace.writeText('dist/components/language/node.gitignore', 'node_modules/\n');
    workspace.writeJson('dist/presets/node.json', {
      name: 'node',
      components: ['platform/macos', 'language/node']
    });

    const resolver = createDefinitionResolver({ distRoot: workspace.path('dist') });
    const content = await generateGitignore({
      config: {
        version: 1,
        name: 'exclude-test',
        preset: 'node',
        exclude: ['platform/macos'],
        provider: { name: 'local' },
        components: [],
        custom: [],
        addons: {}
      },
      resolver
    });

    // Should include language/node but NOT platform/macos
    assert.match(content, /node_modules\//);
    assert.doesNotMatch(content, /\.DS_Store/);
    // Should still reference the preset
    assert.match(content, /Preset: node/);
  } finally {
    workspace.cleanup();
  }
});

// --- #7: .trim() after normalizeText() must not strip leading whitespace ---

test('generator preserves leading whitespace in component patterns', async () => {
  const workspace = createTempWorkspace();
  try {
    // A component whose patterns include leading whitespace (significant in
    // gitignore: a leading space before a pattern is ignored by Git unless
    // escaped with backslash, but the pattern "  leading-space" is a valid
    // gitignore entry that matches a file literally named with leading spaces).
    workspace.writeText('dist/components/local/spacey.gitignore', '  leading-space-rule\nnormal-rule\n');
    workspace.writeJson('dist/presets/demo.json', { name: 'demo', components: ['local/spacey'] });

    const resolver = createDefinitionResolver({ distRoot: workspace.path('dist') });
    const content = await generateGitignore({
      config: {
        version: 1,
        name: 'spacey-project',
        preset: 'demo',
        provider: { name: 'local' },
        components: [],
        custom: [],
        addons: {}
      },
      resolver
    });

    // Leading whitespace in the component pattern must be preserved.
    // The old .trim() after normalizeText() silently stripped it.
    assert.match(content, /  leading-space-rule/);
    assert.match(content, /normal-rule/);
  } finally {
    workspace.cleanup();
  }
});

test('generator skips missing component instead of crashing', async () => {
  const workspace = createTempWorkspace();
  try {
    // Config references a component that does not exist on disk.
    // The generator must skip it gracefully rather than throwing
    // DefinitionNotFoundError.
    workspace.writeJson('dist/presets/demo.json', {
      name: 'demo',
      components: []
    });

    const resolver = createDefinitionResolver({ distRoot: workspace.path('dist') });
    const content = await generateGitignore({
      config: {
        version: 1,
        name: 'missing-component-project',
        preset: 'demo',
        provider: { name: 'local' },
        components: ['local/nonexistent'],
        custom: ['/custom-rule/'],
        addons: {}
      },
      resolver
    });

    // Must not throw — missing component is skipped
    assert.match(content, /Generated by ignorekit/);
    // Custom rules must still appear
    assert.match(content, /\/custom-rule\//);
    // The missing component must not appear in the component list header
    assert.doesNotMatch(content, /local\/nonexistent/);
  } finally {
    workspace.cleanup();
  }
});

// --- #2 (P1): generator must warn on stderr for missing components ---

test('generator writes warning to stderr for missing components', async () => {
  const workspace = createTempWorkspace();
  try {
    // Config references a component that does not exist on disk.
    // The generator must skip it gracefully (not crash) but also write a
    // user-visible warning to stderr so the user knows their config
    // references a component that could not be resolved.
    workspace.writeJson('dist/presets/demo.json', {
      name: 'demo',
      components: []
    });

    const resolver = createDefinitionResolver({ distRoot: workspace.path('dist') });
    const stderrChunks = [];
    const content = await generateGitignore({
      config: {
        version: 1,
        name: 'missing-warning-project',
        preset: 'demo',
        provider: { name: 'local' },
        components: ['local/nonexistent', 'local/also-missing'],
        custom: ['/custom-rule/'],
        addons: {}
      },
      resolver,
      env: {
        stderr: { write: text => stderrChunks.push(String(text)) }
      }
    });

    // Must not throw — missing components are skipped
    assert.match(content, /Generated by ignorekit/);
    // Custom rules must still appear
    assert.match(content, /\/custom-rule\//);
    // The missing components must not appear in the component list header
    assert.doesNotMatch(content, /local\/nonexistent/);
    assert.doesNotMatch(content, /local\/also-missing/);
    // A user-visible warning must appear on stderr for each missing component
    const stderrText = stderrChunks.join('');
    assert.match(stderrText, /local\/nonexistent/,
      'stderr should warn about missing component local/nonexistent');
    assert.match(stderrText, /local\/also-missing/,
      'stderr should warn about missing component local/also-missing');
  } finally {
    workspace.cleanup();
  }
});
