Set-StrictMode -Version Latest

function Get-GisRoot {
    return (Split-Path -Parent $PSScriptRoot)
}

function Get-GisManifestPath {
    return (Join-Path (Get-GisRoot) 'projects.json')
}

function Get-GisManifest {
    $path = Get-GisManifestPath
    if (-not (Test-Path $path)) {
        throw "Manifest not found: $path"
    }
    return (Get-Content $path -Raw | ConvertFrom-Json)
}

function Get-GisProjects {
    return @((Get-GisManifest).projects)
}

function Find-GisProject {
    param(
        [Parameter(Mandatory = $true)]
        [string]$ProjectName,

        [string]$Root
    )

    $matches = @(Get-GisProjects | Where-Object {
        $_.name -eq $ProjectName -and ([string]::IsNullOrWhiteSpace($Root) -or $_.root -eq $Root)
    })

    if ($matches.Count -eq 0) {
        if ([string]::IsNullOrWhiteSpace($Root)) {
            throw "Project '$ProjectName' was not found in projects.json."
        }
        throw "Project '$Root/$ProjectName' was not found in projects.json."
    }

    if ($matches.Count -gt 1) {
        $choices = ($matches | ForEach-Object { "$($_.root)/$($_.name)" }) -join ', '
        throw "Project name '$ProjectName' is ambiguous. Use -Root. Matches: $choices"
    }

    return $matches[0]
}

function Get-GisProfilePath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Profile
    )

    $path = Join-Path (Join-Path (Get-GisRoot) 'profiles') "$Profile.txt"
    if (-not (Test-Path $path)) {
        throw "Profile not found: $path"
    }
    return $path
}

function Get-GisProfileFragments {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Profile
    )

    $repoRoot = Get-GisRoot
    $profilePath = Get-GisProfilePath -Profile $Profile
    $fragmentNames = Get-Content $profilePath |
        ForEach-Object { $_.Trim() } |
        Where-Object { $_ -ne '' -and -not $_.StartsWith('#') }

    foreach ($fragmentName in $fragmentNames) {
        $relativePath = $fragmentName -replace '/', [IO.Path]::DirectorySeparatorChar
        $fragmentPath = Join-Path $repoRoot $relativePath
        if (-not (Test-Path $fragmentPath)) {
            throw "Fragment '$fragmentName' from profile '$Profile' was not found at $fragmentPath"
        }
        $fragmentPath
    }
}

function Read-GisText {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    return [IO.File]::ReadAllText($Path)
}

function Write-GisText {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,

        [Parameter(Mandatory = $true)]
        [string]$Content
    )

    $directory = Split-Path -Parent $Path
    if ($directory -and -not (Test-Path $directory)) {
        New-Item -ItemType Directory -Force $directory | Out-Null
    }

    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    [IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
}

function New-GisProfileProject {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Profile
    )

    return [pscustomobject]@{
        root = 'profiles'
        name = $Profile
        path = ''
        profile = $Profile
        detected = @()
        extraPatterns = @()
    }
}

function New-GisContent {
    param(
        [Parameter(Mandatory = $true)]
        [object]$Project
    )

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add('# Generated by gitignore-standards')
    $lines.Add("# Project: $($Project.root)/$($Project.name)")
    $lines.Add("# Profile: $($Project.profile)")
    $lines.Add('# Edit fragments, profiles, or projects.json, then regenerate.')
    $lines.Add('')

    foreach ($fragmentPath in (Get-GisProfileFragments -Profile $Project.profile)) {
        $fragmentText = (Read-GisText -Path $fragmentPath).Trim()
        if ($fragmentText.Length -gt 0) {
            $lines.Add($fragmentText)
            $lines.Add('')
        }
    }

    $extraPatterns = @()
    if ($null -ne $Project.PSObject.Properties['extraPatterns'] -and $null -ne $Project.extraPatterns) {
        $extraPatterns = @($Project.extraPatterns)
    }

    if ($extraPatterns.Count -gt 0) {
        $lines.Add('# Project-specific ignores')
        foreach ($pattern in $extraPatterns) {
            $lines.Add([string]$pattern)
        }
        $lines.Add('')
    }

    return (($lines -join "`n").TrimEnd() + "`n")
}

function Get-GisGeneratedPath {
    param(
        [Parameter(Mandatory = $true)]
        [object]$Project
    )

    $safeRoot = ([string]$Project.root) -replace '[\\/:*?"<>|]', '_'
    $safeName = ([string]$Project.name) -replace '[\\/:*?"<>|]', '_'
    return (Join-Path (Join-Path (Join-Path (Get-GisRoot) 'generated') $safeRoot) "$safeName.gitignore")
}

function Write-GisRecommendation {
    param(
        [Parameter(Mandatory = $true)]
        [object]$Project,

        [string]$Output
    )

    if ([string]::IsNullOrWhiteSpace($Output)) {
        $Output = Get-GisGeneratedPath -Project $Project
    }

    $content = New-GisContent -Project $Project
    Write-GisText -Path $Output -Content $content
    return $Output
}

function Normalize-GisContent {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Content
    )

    $normalized = $Content -replace "`r`n", "`n"
    $normalized = $normalized -replace "`r", "`n"
    return ($normalized.TrimEnd() + "`n")
}
