'use strict';

const { normalizeText } = require('./core/text');
const { normalizeProjectConfig } = require('./config/project-config');
const { buildProviderText } = require('./providers');
const { resolvePresetComponents } = require('./definitions/resolver');
const { debugError } = require('./core/debug');

async function generateGitignore({ config, resolver, providerOptions = {}, env }) {
  const normalized = normalizeProjectConfig(config);
  const presetComponents = normalized.preset
    ? resolvePresetComponents(resolver, normalized.preset)
    : [];

  // Filter out excluded components from the preset component list
  const excludeSet = new Set(normalized.exclude);
  const filteredPresetComponents = presetComponents.filter(id => !excludeSet.has(id));
  const componentIds = [...new Set([...filteredPresetComponents, ...normalized.components])];

  // Resolve which components can be read — missing components are skipped
  // rather than crashing the entire generation. This also avoids listing
  // unreadable component IDs in the output header.
  const resolvedIds = [];
  const resolvedContent = new Map();
  for (const componentId of componentIds) {
    try {
      const text = normalizeText(resolver.readComponent(componentId)).replace(/\n$/, '');
      resolvedIds.push(componentId);
      resolvedContent.set(componentId, text);
    } catch (err) {
      debugError(err, 'generator.readComponent', env);
    }
  }

  const lines = [
    '# Generated by ignorekit',
    `# Project: ${normalized.name}`,
    normalized.preset ? `# Preset: ${normalized.preset}` : '# Preset: none',
    '# Components:'
  ];

  for (const componentId of resolvedIds) {
    lines.push(`# - ${componentId}`);
  }
  lines.push('# Edit ignorekit.json or shared definitions, then regenerate.');
  lines.push('');

  const providerText = normalizeText(await buildProviderText(normalized.provider, { ...providerOptions, stderr: env && env.stderr })).replace(/\n$/, '');
  if (providerText) {
    lines.push('# Provider templates');
    lines.push(providerText);
    lines.push('');
  }

  for (const componentId of resolvedIds) {
    const componentText = resolvedContent.get(componentId);
    if (componentText) {
      lines.push(componentText);
      lines.push('');
    }
  }

  if (normalized.custom.length > 0) {
    lines.push('# Project-specific ignores');
    for (const pattern of normalized.custom) {
      lines.push(String(pattern));
    }
    lines.push('');
  }

  return normalizeText(lines.join('\n'));
}

module.exports = { generateGitignore };
