'use strict';

const { normalizeText } = require('./core/text');
const { buildProviderText } = require('./providers');
const { resolvePresetComponents } = require('./definitions/resolver');
const { debugError } = require('./core/debug');
const { version: VERSION } = require('../package.json');

/**
 * Generate a .gitignore from a project config. Callers must pass an
 * already-normalized config (via normalizeProjectConfig or buildProjectConfig).
 * The generator does not re-normalize so that validation bugs in callers are
 * caught immediately rather than masked by a second normalization pass.
 */
async function generateGitignore({ config, resolver, providerOptions = {}, env }) {
  const normalized = config;
  const presetComponents = normalized.preset
    ? resolvePresetComponents(resolver, normalized.preset)
    : [];

  // Filter out excluded components from the preset component list
  const excludeSet = new Set(normalized.exclude);
  const filteredPresetComponents = presetComponents.filter(id => !excludeSet.has(id));
  const componentIds = [...new Set([...filteredPresetComponents, ...normalized.components])];

  // Resolve which components can be read — missing components are skipped
  // rather than crashing the entire generation. After the loop, any
  // components that could not be resolved are reported to stderr so the
  // user knows their config references a component that doesn't exist,
  // rather than silently getting a .gitignore that omits rules they expect.
  const resolvedIds = [];
  const resolvedContent = new Map();
  for (const componentId of componentIds) {
    try {
      const text = normalizeText(resolver.readComponent(componentId)).replace(/\n$/, '');
      resolvedIds.push(componentId);
      resolvedContent.set(componentId, text);
    } catch (err) {
      debugError(err, 'generator.readComponent', env);
    }
  }

  // Report missing components to stderr. Without this warning, a typo in
  // ignorekit.json (e.g. "laguage/java" instead of "language/java") silently
  // produces a .gitignore that omits the intended rules — the user sees no
  // error and may not realize anything is wrong until rules they expected are
  // missing from the generated output.
  const missingIds = componentIds.filter(id => !resolvedIds.includes(id));
  if (missingIds.length > 0) {
    const stderr = (env && env.stderr) || process.stderr;
    for (const id of missingIds) {
      stderr.write(`Warning: component "${id}" not found — skipping.\n`);
    }
  }

  const lines = [
    `# Generated by ignorekit v${VERSION}`,
    `# Project: ${normalized.name}`,
    normalized.preset ? `# Preset: ${normalized.preset}` : '# Preset: none',
    '# Components:'
  ];

  for (const componentId of resolvedIds) {
    lines.push(`# - ${componentId}`);
  }
  lines.push('# Edit ignorekit.json or shared definitions, then regenerate.');
  lines.push('');

  const providerText = normalizeText(await buildProviderText(normalized.provider, { ...providerOptions, stderr: env && env.stderr })).replace(/\n$/, '');
  if (providerText) {
    lines.push('# Provider templates');
    lines.push(providerText);
    lines.push('');
  }

  for (const componentId of resolvedIds) {
    const componentText = resolvedContent.get(componentId);
    if (componentText) {
      lines.push(componentText);
      lines.push('');
    }
  }

  if (normalized.custom.length > 0) {
    lines.push('# Project-specific ignores');
    for (const pattern of normalized.custom) {
      lines.push(String(pattern));
    }
    lines.push('');
  }

  return normalizeText(lines.join('\n'));
}

module.exports = { generateGitignore };
