'use strict';

const { normalizeText } = require('./core/text');
const { resolvePresetComponents } = require('./definitions/resolver');
const { debugError } = require('./core/debug');
const { extractStreams } = require('./core/env');
const { version: VERSION } = require('../package.json');

/**
 * Generate a .gitignore from a project config. Callers must pass an
 * already-normalized config (via normalizeProjectConfig or buildProjectConfig).
 * The generator does not re-normalize so that validation bugs in callers are
 * caught immediately rather than masked by a second normalization pass.
 *
 * @param {object} params
 * @param {object} params.config - Normalized project config
 * @param {object} params.resolver - Definition resolver
 * @param {object} [params.env] - Environment object. Should contain at least
 *   `{ stderr }` for warning output. When env is missing or partial, extractStreams
 *   (called internally) provides fallbacks to process.stdout, process.stderr, and
 *   process.cwd — so callers that omit env still work, but warnings go to
 *   process.stderr rather than a test-capturable stream. Passing env through
 *   extractStreams at the caller's boundary is recommended so that every function
 *   in the chain has a consistent safety net.
 */
async function generateGitignore({ config, resolver, env }) {
  const { stderr } = extractStreams(env);
  const normalized = config;
  const presetComponents = normalized.preset
    ? resolvePresetComponents(resolver, normalized.preset)
    : [];

  // Filter out excluded components from the preset component list
  const excludeSet = new Set(normalized.exclude);
  const filteredPresetComponents = presetComponents.filter(id => !excludeSet.has(id));
  const componentIds = [...new Set([...filteredPresetComponents, ...normalized.components])];

  // Resolve which components can be read — missing components are skipped
  // rather than crashing the entire generation. After the loop, any
  // components that could not be resolved are reported to stderr so the
  // user knows their config references a component that doesn't exist,
  // rather than silently getting a .gitignore that omits rules they expect.
  const resolvedIds = [];
  const resolvedContent = new Map();
  for (const componentId of componentIds) {
    try {
      const text = normalizeText(resolver.readComponent(componentId)).replace(/\n$/, '');
      resolvedIds.push(componentId);
      resolvedContent.set(componentId, text);
    } catch (err) {
      debugError(err, 'generator.readComponent', env);
    }
  }

  // Report missing components to stderr. Without this warning, a typo in
  // ignorekit.json (e.g. "laguage/java" instead of "language/java") silently
  // produces a .gitignore that omits the intended rules — the user sees no
  // error and may not realize anything is wrong until rules they expected are
  // missing from the generated output.
  const missingIds = componentIds.filter(id => !resolvedIds.includes(id));
  if (missingIds.length > 0) {
    for (const id of missingIds) {
      stderr.write(`Warning: component "${id}" not found — skipping.\n`);
    }
  }

  const lines = [
    `# Generated by ignorekit v${VERSION}`,
    `# Project: ${normalized.name}`,
    normalized.preset ? `# Preset: ${normalized.preset}` : '# Preset: none',
    '# Components:'
  ];

  for (const componentId of resolvedIds) {
    lines.push(`# - ${componentId}`);
  }
  lines.push('# Edit ignorekit.json or shared definitions, then regenerate.');
  lines.push('');

  // Components are the primary building blocks of the generated .gitignore.
  // Project-specific rules follow them so local overrides remain last.
  for (const componentId of resolvedIds) {
    const componentText = resolvedContent.get(componentId);
    if (componentText) {
      lines.push(componentText);
      lines.push('');
    }
  }

  if (normalized.custom.length > 0) {
    lines.push('# Project-specific ignores');
    for (const pattern of normalized.custom) {
      lines.push(String(pattern));
    }
    lines.push('');
  }

  return normalizeText(lines.join('\n'));
}

module.exports = { generateGitignore };
